wordlist_hira = ['まど', 'しお', 'きた', 'めい', 'さば', 'ばん', 'かい', 'まつ', 'きも', 'つち', 'はは', 'おく', 'ねる',
                 'とき', 'かぜ', 'うま', 'えり',
                 'はち', 'へび', 'たい', 'さる', 'ひも', 'ぎん', 'うつ', 'へる', 'わし', 'かく', 'まん', 'おる', 'ちゃ',
                 'うる', 'どう', 'くび', 'つき', 'すね', 'おば',
                 'みせ', 'くき', 'むぎ', 'とる', 'なな', 'いね', 'いち', 'まめ', 'かぐ', 'たか', 'はれ', 'むし', 'あく',
                 'しり', 'さん', 'そら', 'くま', 'はく', 'いい',
                 'むく', 'ゆき', 'ねこ', 'えき', 'さす', 'せる', 'はば', 'ひざ', 'はな', 'こむ', 'さつ', 'のむ', 'もつ',
                 'みず', 'ほね', 'あさ', 'もも', 'れい', 'そで',
                 'かむ', 'きん', 'しぬ', 'くさ', 'くろ', 'ひじ', 'ひふ', 'せみ', 'いく', 'よる', 'てつ', 'あじ', 'そふ',
                 'とり', 'つま', 'かた', 'かう', 'かみ', 'うで',
                 'ふで', 'いえ', 'とぶ', 'つめ', 'もじ', 'あね', 'いも', 'みぎ', 'なわ', 'まえ', 'ちち', 'あう', 'あし',
                 'いま', 'ちり', 'くぎ', 'ほし', 'しる', 'しろ',
                 'げり', 'とお', 'はだ', 'あか', 'うむ', 'ひる', 'いる', 'うし', 'うめ', 'しか', 'いう', 'ぼく', 'とし',
                 'れる', 'よん', 'ゆび', 'ふく', 'ます', 'えび',
                 'かね', 'おれ', 'むね', 'した', 'える', 'ひと', 'くつ', 'おじ', 'くち', 'こめ', 'あお', 'かお', 'あに',
                 'たつ', 'くる', 'がま', 'みる', 'みそ', 'いす',
                 'きる', 'ひげ', 'ほん', 'みち', 'ゆげ', 'かさ', 'ける', 'ぶた', 'にく', 'とら', 'りか', 'かぎ', 'ない',
                 'どろ', 'なく', 'ろく', 'ふん', 'よむ', 'かこ',
                 'そぼ', 'おい', 'ぞう', 'いろ', 'いぬ', 'にし', 'きく', 'まご', 'しし', 'みみ', 'あめ', 'こし', 'うえ',
                 'せん', 'あつい', 'じしょ', 'あける', 'かるい',
                 'こぜに', 'おちゃ', 'さむい', 'いしゃ', 'わふく', 'わるい', 'みっつ', 'おこる', 'にっき', 'さとう',
                 'いとこ', 'からす', 'むっつ', 'おっと', 'おやつ', 'かしゅ',
                 'つくえ', 'やすむ', 'たべる', 'きのう', 'わたし', 'あそぶ', 'ひつじ', 'はなす', 'みだす', 'こども',
                 'うさぎ', 'ふとん', 'きいろ', 'ねずみ', 'おなか', 'ひゃく',
                 'しめる', 'ほそい', 'あまい', 'およぐ', 'かわく', 'しかる', 'あらし', 'すわる', 'からい', 'おんな',
                 'すごい', 'ひみつ', 'さかな', 'ふとる', 'こわい', 'すずめ',
                 'うごく', 'しまい', 'こころ', 'くるま', 'ななめ', 'ふたつ', 'うしろ', 'でんき', 'あきる', 'ひだり',
                 'くさい', 'こおり', 'あたま', 'たたみ', 'かいぎ', 'ほめる',
                 'かつお', 'じゅう', 'ふくろ', 'にがい', 'なおす', 'てまえ', 'ようび', 'きって', 'いつつ', 'ふるい',
                 'すうじ', 'ごはん', 'わらう', 'おもい', 'こちら', 'きもの',
                 'かたい', 'いわし', 'わかい', 'あちら', 'みなみ', 'どうろ', 'いたい', 'えいご', 'おどる', 'かえる',
                 'みどり', 'れきし', 'やすい', 'くもり', 'きのこ', 'きょう',
                 'つらい', 'いきる', 'さくら', 'ひえる', 'うまる', 'きゅう', 'あした', 'なまり', 'まぐろ', 'きめる',
                 'なげる', 'なぐる', 'めがね', 'あるく', 'とおい', 'かたる',
                 'しかい', 'ひがし', 'うたう', 'きっぷ', 'けむり', 'せなか', 'おわる', 'たかい', 'かぞく', 'びょう',
                 'おとこ', 'はしる', 'しゅう', 'あたし', 'やさい', 'よっつ',
                 'ちょう', 'こよみ', 'つかう', 'むこう', 'まずい', 'りゅう', 'じかん', 'へいし', 'みらい', 'かばん',
                 'とおり', 'つくる', 'くうき', 'てくび', 'かかと', 'じどう',
                 'すてる', 'やっつ', 'ふえる', 'さめる', 'はさみ', 'さんま', 'さわる', 'てんき', 'ふとい', 'どちら',
                 'かんじ', 'ひとつ', 'うまい', 'そちら', 'いらい', 'ひくい',
                 'とびら', 'ななつ', 'ちかい', 'かゆい', 'てがみ', 'ひつよう', 'きんにく', 'せいじか', 'しんぶん',
                 'はずれる', 'しょうゆ', 'ちいさい', 'よろこぶ', 'つかえる', 'かみなり',
                 'たこやき', 'わかれる', 'こわれる', 'よろこび', 'たてもの', 'おどろく', 'りょうり', 'そなわる',
                 'げんざい',
                 'どうぶつ', 'かたまる', 'つりせん', 'はじまる', 'さみしい',
                 'かいしゃ', 'つめたい', 'どようび', 'たべもの', 'かんごし', 'おとうと', 'のみもの', 'みだれる',
                 'くちびる',
                 'ひらがな', 'たいよう', 'わかもの', 'にほんご', 'ばけもの',
                 'たのしい', 'じょうぎ', 'すぐれる', 'くうこう', 'いきもの', 'てつどう', 'ゆうがた', 'ふうとう',
                 'おおきい',
                 'ちゃいろ', 'おんがく', 'だいこん', 'うもれる', 'きょうし',
                 'けいざい', 'でんしゃ', 'しんぞう', 'さんすう', 'えんぴつ', 'しゃかい', 'いもうと', 'かいがら',
                 'つかれる',
                 'ひこうき', 'かんごふ', 'きんぞく', 'にんじん', 'くだもの',
                 'じんるい', 'かなしむ', 'ここのつ', 'むらさき', 'てのひら', 'がっこう', 'ようふく', 'わたくし',
                 'せいしき',
                 'くつした', 'どいつご', 'かなしい', 'はいいろ', 'たいいく',
                 'おぼえる', 'やくしょ', 'おいしい', 'かようび', 'でかける', 'けっこん', 'せんせい', 'びょうき',
                 'げんかん',
                 'うれしい', 'にわとり', 'たおれる', 'たいふう', 'かんぞう',
                 'あつまる', 'にんげん', 'やさしい', 'おしえる', 'はたらく', 'さびしい', 'ないよう', 'べんごし',
                 'ゆうしょう', 'きょうだい', 'よかったら', 'きゅうよう', 'かんけいが',
                 'しゅしょう', 'がいこくじ', 'にじゅうね', 'しょくぶつ', 'なくします', 'そだてます', 'そのままに',
                 'おんがくが', 'こんやくし', 'いきません', 'えいぎょう', 'でんげんを',
                 'ほけんしょ', 'あきはばら', 'くらします', 'つれていき', 'だいどころ', 'じゅういっ', 'ごめんくだ',
                 'まがります', 'あさごはん', 'おとこのこ', 'けしょうひ', 'おかあさん',
                 'ゆしゅつし', 'っているよ', 'すみません', 'こんにちは', 'えていませ', 'おいそがし', 'あるんです',
                 'なりました', 'おねえさん', 'ゆうびんき', 'かわきます', 'こうしえん',
                 'むかいます', 'はじめます', 'おやこどん', 'じょうほう', 'けずります', 'あらいます', 'まだまだで',
                 'もらいます', 'うつくしい', 'まいにちや', 'かよいます', 'そうきょく',
                 'ちょうなん', 'けがをしま', 'じてんしゃ', 'おとうさん', 'いっしょう', 'もくようび', 'ゆっくりし',
                 'しゅじんこ', 'しゅっぱつ', 'かいじょう', 'でかけます', 'じどうしゃ',
                 'ひらきます', 'あんないし', 'かいぎしつ', 'こうじょう', 'すばらしい', 'おしえます', 'どうですか',
                 'うちゅうひ', 'はしります', 'すごします', 'しゅうにゅ', 'ごしゅじん',
                 'びじゅつか', 'かかります', 'れんしゅう', 'じょうずに', 'たのみます', 'なりません', 'きょうりょ',
                 'のかわりに', 'あつまりま', 'おじいさん', 'たったいま', 'ごくろうさ',
                 'れいぞうこ', 'ぎゅうにく', 'じゅぎょう', 'めしあがり', 'みつけます', 'にんぎょう', 'どうぶつえ',
                 'ひじょうぐ', 'さらいしゅ', 'りょうしん', 'しょうらい', 'しかります',
                 'ゆるめます', 'つかれます', 'なつやすみ', 'あたります', 'こんしゅう', 'おべんとう', 'しまいます',
                 'ひるごはん', 'むかえます', 'しゅくだい', 'たしかめま', 'べんきょう',
                 'あたらしい', 'おめでとう', 'おばあさん', 'たすかりま', 'とおります', 'ならびます', 'じゅんびが',
                 'よういしま', 'おこないま', 'とどけます', 'ことですね', 'あらわれる',
                 'しょうせつ', 'えいがかん', 'くらべます', 'しませんね', 'しょくどう', 'でんわだい', 'じゅうどう',
                 'ちょうこく', 'わかりまし', 'すばらしさ', 'わかれます', 'しらべます',
                 'ありません', 'むずかしい', 'おもしろい', 'さんぽしま', 'きょうそう', 'すぺいんご', 'せんたくし',
                 'わらいます', 'せんたくき', 'しつれいい', 'えらびます', 'つづけます',
                 'さらいげつ', 'やわらかい', 'いただきま', 'わかりませ', 'しょっぱい', 'ぶんぼうぐ', 'まいしゅう',
                 'じゅうなな', 'あたたかい', 'けんさしま', 'せかいてき', 'つまらない',
                 'いらっしゃ', 'げつようび', 'まにあいま', 'かんたんに', 'きんようび', 'にゅうがく', 'さらいねん',
                 'れさまでし', 'なんかいも', 'があります', 'しゅっちょ', 'にほんから',
                 'らいしゅう', 'きゅうきゅ', 'とっきゅう', 'おさきにど', 'ひまわりし', 'きをつけま', 'おとうとさ',
                 'おとします', 'しょうかい', 'おぼえます', 'ってくださ', 'ひるやすみ',
                 'ほんとうに', 'しんかんせ', 'びょういん', 'とらえます', 'しょうねん', 'じゅうよん', 'ぞんじます',
                 'のみましょ', 'あかちゃん', 'とどきます', 'こどものひ', 'もどします',
                 'うちゅうせ', 'がいこくご', 'けいさんし', 'うんどうか', 'しゅうりし', 'さんかしま', 'よろしいで',
                 'おんなのこ', 'あつめます', 'おにいさん', 'こんばんは', 'しいですか',
                 'のこります', 'すわります', 'おてあらい', 'おかえりな', 'どうしまし', 'けんちくか', 'すいようび',
                 'ばんごはん', 'たいしかん', 'こまったな', 'しやくしょ', 'じゅんじょ',
                 'はじめまし', 'いけません', 'なぐさめる', 'ほしょうし', 'がんばって', 'はずれます', 'せいじんし',
                 'しんぶんし', 'はいります', 'へいきんじ', 'そのとおり', 'だめですか',
                 'にちようび', 'ほんとうだ', 'しょうじょ', 'そうですね', 'せいようか', 'うごきます', 'せんしゅう',
                 'いもうとさ', 'かんりにん', 'しつもんに', 'せわをしま', 'きっさてん',
                 'やすみます', 'いそがしい', 'しょうしょ', 'ばんりのち', 'にゅうりょ', 'ふらんすご', 'としょかん',
                 'きゅうりょ', 'きょうしつ', 'おっしゃいる', 'しょうせつか', 'ちょうどいい',
                 'つれてきます', 'かいしゃいん', 'こうじちゅう', 'いただきます', 'けんぶつしま', 'あやまります',
                 'ぶつかります', 'とりかえます', 'ありませんか', 'ちこくします', 'おきゃくさま',
                 'けっこんしき', 'せいじんしき', 'まだまだです', 'よていひょう', 'しようちゅう', 'はんばいてん',
                 'なくなります', 'たすかります', 'うろくしょう', 'おこないます', 'わかりません',
                 'れさまでした', 'たのしみます', 'うんどうかい', 'けがをします', 'しようきんし', 'きゅうりょう',
                 'いっぱいです', 'なりませんか', 'いもうとさん', 'りょこうしゃ', 'うちゅうせん',
                 'ぎんこういん', 'いいんですか', 'さらいしゅう', 'すんでいます', 'みつかります', 'ごぞんじです',
                 'どうぶつえん', 'きをつけます', 'しゅうにゅう', 'がいこくじん', 'しゅっちょう',
                 'せんたくもの', 'とりつけます', 'あきらめます', 'もっています', 'せかいてきに', 'ちょうせんご',
                 'けしょうひん', 'じゅんじょが', 'かたづけます', 'こまったこと', 'だいじょうぶ',
                 'じこくひょう', 'がありますか', 'うんてんしゅ', 'もってきます', 'たくはいびん', 'たんじょうび',
                 'ほけんしょう', 'ごちそうさま', 'おっしゃいて', 'あずかります', 'もとのところ',
                 'あんないしょ', 'ちょうしょく', 'ひじょうぐち', 'かいぎちゅう', 'よやくします', 'ぎゅうにゅう',
                 'すごいですね', 'てつだいます', 'ぼうねんかい', 'せかいじゅう', 'くろうします',
                 'かまいません', 'じゅうきゅう', 'まんねんひつ', 'びじゅつかん', 'ぎおんまつり', 'はたらきすぎ',
                 'たいおんけい', 'まとめるのに', 'ほしょうしょ', 'よういします', 'けっこうです',
                 'のりかえます', 'しゅじんこう', 'ありませんね', 'けいさつかん', 'こうじょうが', 'いきましたね',
                 'くみたてます', 'ごくろうさま', 'それほどでも', 'しっています', 'うかがいます',
                 'しんぶんしゃ', 'あんぜんぐつ', 'あつまります', 'しんかんせん', 'むかしばなし', 'はじまります',
                 'だいがくいん', 'てんきよほう', 'いけませんね', 'じょうほうが', 'おとうとさん',
                 'さんぽします', 'せわをします', 'なさいますか', 'すてきですね', 'ぎじゅつしゃ', 'もしかしたら',
                 'おとこのひと', 'まにあいます', 'おいそがしい', 'がありません', 'てんらんかい',
                 'たしかめます', 'おんなのひと', 'ごしゅっせき', 'よかったです', 'がんばります', 'はじめまして',
                 'うわさします', 'わかりました', 'ってください', 'たいいくかん', 'さんかします',
                 'はくぶつかん', 'しょうぼうし', 'けんかします', 'べんきょうを', 'しんねんかい', 'のみましょう',
                 'そうべつかい', 'えていません', 'すみませんが', 'むりをします', 'くださいます',
                 'しょうしょう', 'いらっしゃい', 'けんさします', 'してください', 'せいりします', 'ちゅうごくご',
                 'はたらきます', 'いかがですか', 'そうじします', 'べんきょうに', 'りこんします',
                 'うごかします', 'おかげさまで', 'でんわします', 'だいとうりょう', 'おでかけですか', 'けんしゅうせい',
                 'なんでしょうか', 'よろしいでしょ', 'にじゅうねんご', 'りょうしゅうし',
                 'めざましどけい', 'もうしわけあり', 'せんたくします', 'そうしましょう', 'いいてんきです',
                 'ほうそうします',
                 'まちがいでんわ', 'しゅうりします', 'どういうふうに', 'あいさつします',
                 'けんしゅうりょ', 'しんぱいします', 'はっけんします', 'おめにかかりま', 'たいいんします',
                 'ゆうびんきょく',
                 'きょうりょくし', 'けいさんします', 'けんきゅうしま', 'おねがいできま',
                 'しょくじします', 'ちょうみりょう', 'ごめんください', 'がっかりします', 'こまかいおかね',
                 'うんどうします',
                 'どうでしょうか', 'しゅっせきしま', 'いがあるんです', 'ゆしゅつします',
                 'びっくりします', 'おげんきですか', 'ばんりのちょう', 'はっぴょうしま', 'こうそくどうろ',
                 'ほんやくします',
                 'しんせつにしま', 'ちょきんします', 'おっしゃいます', 'たちいりきんり',
                 'けんきゅうしゃ', 'それはいけませ', 'ほんじつきゅう', 'うちゅうひこう', 'せいようかしま',
                 'ほんとうですか',
                 'おぼえていませ', 'ゆっくりします', 'おめでとうござ', 'かわりをします',
                 'いいでしょうか', 'じゅじょうしま', 'いらっしゃいて', 'ようせつします', 'おねがいします',
                 'おかえりなさい',
                 'そうたいします', 'だいじょうぶで', 'じゅぎょうちゅ', 'ひまわりしょう',
                 'いらっしゃいま', 'しょうたいしま', 'おやこどんぶり', 'おあがりくださ', 'いっしょにいき',
                 'おいそがしいで',
                 'つうしんはんば', 'へいきんじゅみ', 'きゅうきゅうし', 'はつめいします',
                 'いらっしゃいる', 'れんしゅうしま', 'がってください', 'けっこんします', 'えんりょくなく',
                 'あんしょうばん',
                 'じどうはんばい', 'もっていきます', 'いっぱんけんし', 'なににつかいま',
                 'はいけんします', 'ゆにゅうします', 'ゆうしょうしま', 'かんしゃします', 'にゅうりょくし',
                 'どちらさまでし',
                 'ぶんがくしょう', 'そのとおりです', 'けんがくします', 'りゅうがくせい',
                 'えんぴつけずり', 'がいこくじんと', 'しゅっぱつしま', 'しつれいいたし', 'しつれいですが',
                 'はありませんか',
                 'かんさいくうこ', 'しばらくですね', 'きんちょうしま', 'いらっしゃって',
                 'つれていきます', 'じゅんびします', 'やりなおします', 'ちゅうしゃいは', 'しゅっちょうし',
                 'にほんほうそう',
                 'もうしこみます', 'おせわになりま', 'かんせいします', 'かいものします',
                 'おつかれさまで', 'くろうしました', 'いっていらっし', 'たすかりました', 'にちようだいく',
                 'いっしゅうかん',
                 'めしあがります', 'どうしましたか', 'ながいきします', 'えいぎょうちゅ',
                 'いってまいりま', 'ざんぎょうしま', 'くださいまして', 'とうちゃくしま', 'かしこまりまし',
                 'せっけいします',
                 'ちゅうしゃじょ', 'おもいだします', 'おさきにどうぞ', 'うんてんします',
                 'こんやくします', 'せいさんします', 'にゅういんしま', 'よんぶんのいち']

wordlist_hira_translated = ['window, counter, contact person', 'salt, hardship, saltiness',
                            'north, the north, north korea',
                            'niece, first name, famous', 'mackerel, server, atlantic mackerel',
                            'evening, dinner, number',
                            'storey, stairs, stage', 'to wait, to await, to depend on', 'liver, courage, crux',
                            'earth, the earth,',
                            'mother, aha!, yes sir', 'to put, to leave, to establish',
                            'to sleep, to go to bed, to lie down',
                            'time, occasion, chance', 'common cold, wind, manner',
                            'horse, horse racing, promoted bishop',
                            'collar, nape of the neck, fishing weir', 'eight, bowl, flowerpot', 'snake, serpent, heavy',
                            'sea bream, tai, sparidae', 'monkey, sly person, idiot', 'string, leash, restrictions',
                            'silver, silver coin, silver medal', 'to hit, to strike, to beat',
                            'to decrease, to pass, to pass through',
                            'eagle, i, washi', 'to write, to draw, status', '10, myriad, everything',
                            'to break, to fold, to make',
                            'tea, tea plant, tea preparation', 'to sell, to betray, to make', 'copper, bronze, trunk',
                            'neck, head, dismissal',
                            'moon, month, moonlight', 'shin, sponging, snake', 'aunt, old lady, grandmother',
                            'store, to show, to make',
                            'stalk, plant stem, cave', 'wheat, shameless, barley tea', 'to take, to pass, to get',
                            "seven, four o'clock, slanting", 'rice plant, nodding off, rice reaping',
                            'place, position, one',
                            'legume, soya bean, female genitalia', 'furniture, to sniff, very stupid',
                            'hawk, quantity, degree',
                            'clear weather, formal, swelling', 'insect, worm, nervousness',
                            'evil, to open, to be empty',
                            'buttocks, undersurface, last place', 'three, acid, sourness',
                            'sky, weather, far-off place',
                            'bear, corner, shade', 'to put on, to affix, to sweep', 'good, sufficient, profitable',
                            'to turn toward, to face, to point', 'snow, the way there, bound for ...',
                            'cat, shamisen, geisha',
                            'railway station, liquid', 'to shine, to be visible, to be tinged with', 'cell, serge, cel',
                            'width, freedom, gap',
                            'knee, lap, sunlight', 'flower, cherry blossom, beauty',
                            'to be crowded, to be complex, to go into',
                            'banknote, counter for books, volume', 'to drink, to smoke, to engulf',
                            'to hold, to possess, to maintain',
                            'water, fluid, flood', 'bone, frame, outline', 'morning, breakfast, cannabis',
                            'peach, thigh, femoral',
                            'thanks, manners, bow', 'sleeve, wing, flap', 'to bite, to chew, to crash against',
                            'gold, money, sum',
                            'to die, to lose spirit, to cease', 'grass, ninja, marijuana', 'black, black stone, guilt',
                            'elbow, secret, emergency', 'skin, non-negative, skin disease', 'cicada, semi-, seminar',
                            'to go, to move through, to do', 'evening, dinner, night', 'iron, steel, railway',
                            'flavor, charm, experience',
                            'grandfather, old man, sofu', 'bird, bird meat, the rooster',
                            'wife, garnish, accompaniment',
                            'shoulder, type, mold', 'to buy, to value, to incur', 'paper, god, incredible',
                            'arm, skill, ude',
                            'writing brush, writing, ink brush', 'house, family, lineage',
                            'to fly, to jump, to spatter',
                            'nail, plectrum, hook', 'letter, writing, writing system',
                            'older sister, ane, sister-in-law', 'tuber, yokel, dud',
                            'right, right hand, the above', "rope, policeman's rope, skipping rope",
                            'in front, before, forward',
                            'milk, breast, loop', 'to meet, to come together, to fit', 'foot, leg, gait',
                            'living room, now, another',
                            'geography, dust, trash', 'nail, ward assemblyman, sacrifice', 'star, dot, bullseye',
                            'to know, to sense, to understand', 'white, innocence, blank space',
                            'diarrhea, guerrilla, sudden',
                            'ten, ten years of age, distant', 'skin, body, surface', 'red, red light, red ink',
                            'consent or refusal, to give birth, to produce', 'noon, daytime, lunch',
                            'to be, to stay, to be ...-ing',
                            'cattle, beef, the ox', 'japanese apricot, lowest, prunus mume', 'deer, dentistry, dental',
                            'to say, to name, to go', 'i, you, manservant', "year, age, past one's prime", 'rail bus',
                            'four, forty, four thousand', 'finger, ring, to point at', 'clothes, to blow, to play',
                            'to increase, box, square on a grid', 'prawn, ebi, shrimp', 'bell, money, metal',
                            'i, fold, you',
                            'chest, breasts, heart', 'tongue, below, bottom',
                            'to get, to understand, to be able to ...',
                            'person, human beings, human', 'shoe, socks, sock', 'uncle, old man, grandfather',
                            'mouth, opening, gate',
                            'staple, the nth, comment', 'blue, green, green light', 'face, look, honor',
                            'older brother, never, why',
                            'to stand, to be, to leave', 'to come, to come back, to come to be',
                            'common cattail, toad, endurance',
                            'to see, to examine, to look after', 'miso, innards, key', 'chair, post, swords',
                            'to wear, to take, to cut',
                            'moustache, whiskers, shadow', 'book, this, main', 'road, route, distance',
                            'steam, flattering words, to boil with rage', 'umbrella, bulk, conical hat',
                            'to kick, to refuse, to stamp',
                            'pig, pork, fatso', 'flesh, meat, the physical body', 'tiger, drunkard, the tiger',
                            'science, pear blossoms, plum blossoms', 'key, lock, hook', 'nonexistent, unowned, unique',
                            'mud, thief, theft',
                            'to make sound, to cry, nak', 'six, satisfactory, landmass', 'minute, fun, hmm',
                            'to read, to recite, to predict',
                            "the past, one's past, past", 'grandmother, simple, rough', 'old age, nephew, hey!',
                            'elephant, image, figure',
                            'colour, complexion, look', 'dog, squealer, loser', 'west, two out, private',
                            'to hear, to listen, to ask',
                            'grandchild, packhorse driver, ma gu', 'lion, left-hand, flesh', 'ear, hearing, edge',
                            'rain, rainy day, the november suit', 'lower back, body, waist', 'above, top, surface',
                            'thousand, line, ray',
                            'hot, passionate, zealous', "dictionary, estate, one's own writing",
                            'to open, to empty, to move out',
                            'light, non-serious, slight', 'small change, change purse', 'tea, tea break, tea ceremony',
                            'cold, uninteresting, samue', 'doctor, consolation, relying on', 'japanese clothes, kimono',
                            'bad, poor, evil',
                            'three, three cs, adultery', 'to get angry, to scold, to occur',
                            'diary, japan and greece, cinnamon',
                            'sugar, drinker, left-wing party', "cousin, cousin marriage, parent's cousin",
                            'crow, chinese puffer, to let dry',
                            "six, six years of age, six o'clock", 'husband, uh-oh, fur seal',
                            'mid-afternoon, snack break',
                            'singer, good taste, distilled liquor', 'desk, legs of a table, to sit at a desk',
                            'to be absent, to rest, to go to bed', 'to eat, to live on',
                            'yesterday, function, induction',
                            'i, ferry, delivery', 'to play, to mess about, to be idle',
                            'sheep, the sheep, hour of the sheep',
                            'to talk, to tell, to speak', 'to find out, to select, to look out', 'child, children,',
                            'rabbit, rabbit hutch, lepus', 'futon, gabion, drying a futon', 'yellow, high-pitched',
                            'mouse, dark gray, muroidea', 'belly, to become hungry, to feel hungry',
                            'hundred, hyaku, farmer',
                            'to tie, to wear, to total', 'thin, unlucky, fine thread',
                            'sweet-tasting, fragrant, lightly salted',
                            'to swim, to totter', 'to get dry, to be thirsty, to thirst for',
                            'to scold, a particular, that kind of',
                            'storm, uproar, raising havoc', 'to sit, to assume, to hold steady', 'spicy, salty, harsh',
                            'woman, female lover, girl', 'terrible, amazing, to a great extent',
                            'secret, mystery, secrecy', 'fish, sakana',
                            'to put on weight', 'scary, tough, inflexible', 'tree sparrow, talkative person, hornet',
                            'to move, to operate, to make a move', 'sisters, end, sister city', 'mind, to know, to',
                            'car, wheel, rickshaw',
                            'slanting, distorted, oblique incidence', 'two, notification, nondelivery',
                            'back, back-facing, backward-looking',
                            'electricity, biography, electric', 'to get tired of, to become sated, oqil oqilov',
                            'left, left hand, the left',
                            'stinking, suspicious, clumsy', 'ice, shaved ice, district', 'head, hair, mind',
                            'tatami mat, tatami-matted, convolution', 'meeting, doubt, explanation', 'to praise',
                            'skipjack tuna, katsuobushi',
                            'gun, firearm, ten', 'bag, skin of an orange, dead end',
                            'bitter, bitter medicine, bitter experience',
                            'to repair, to change, to put back', "before oneself, one's standpoint, skill",
                            'day of the week, raising the anchor, windlass', 'stamp, postage stamp, stamp album',
                            "five, five years of age, eight o'clock", 'old, long, stale',
                            'numeral, numerical digit, several times',
                            'cooked rice, meal, misjudgement', 'to laugh, to smile, to sneer', 'heavy, slow, important',
                            'this way, here, this', 'kimono, clothing, kimono material', 'hard, stiff, strong',
                            'pilchard, halite, chukar partridge', 'young, immature, low', 'that way, that, that person',
                            'south, southeast, south side', 'road, road sign, traffic sign',
                            'painful, cringy, clothes and obi',
                            'english, english language, intelligent', 'to dance, to jump up, to move around',
                            'to return, to leave, to get home', 'green, greenery, perna viridis',
                            'history, roadkill, historical',
                            'cheap, calm, easy', 'cloudiness, fog, gloom', 'mushroom, kinoko, mushrooming',
                            'today, these days, lord',
                            'painful, tough, cruel', 'to live, to make a living, to be in effect',
                            'cherry tree, fake buyer, hired applauder',
                            'to grow cold', 'to be buried, to overflow, to be repaid', 'sudden, urgent, steep',
                            'tomorrow, near future, morning', 'lead, accent, dialect', 'tuna, dead lay, thunnus',
                            'to decide, to clinch, to always do', 'to throw, to give up, to cast',
                            'to strike, naglfar, naglfari',
                            'glasses, judgment, megane', 'to walk, arcturus, alkmaar', 'far, distant, hard',
                            'to talk about, to recite, to indicate', 'leading a meeting, chairman, presenter',
                            'east, dried candies, higashi',
                            'to sing, to sing of, to extol', 'ticket, character, kip', 'smoke, tobacco, tobacco plant',
                            'back, human back, back to back', 'to end, to finish, to finish doing',
                            'high, expensive, loud',
                            'family, peerage, kazoku', 'second, arc second, rivet', 'man, fellow, male lover',
                            'to run, to rush, to retreat',
                            'week, state, continent', 'i, we, my family', 'vegetable, vegetable soup, crisper',
                            "four, four years of age, ten o'clock", 'butterfly, super-, extremely',
                            'calendar, calendar reform', 'to use',
                            'opposite side, over there, the other party', 'bad, poor, ugly',
                            'dragon, naga, promoted rook',
                            'time, hour, period', 'soldier, heike family, taira clan',
                            'future existence, future, taste bud',
                            'bag, paper bag, going off duty', 'street, traffic, flow', 'to make, to prepare, to raise',
                            'air, mood, emptiness',
                            'wrist', 'heel, axe kick', 'automatic, intransitive verb, children',
                            'to throw away, to abandon, to give up',
                            "eight, two o'clock, to beat", 'to increase, fuerza 2011, fuerteventura',
                            'to wake, to become sober, to cool down',
                            'scissors, hole punch, pincers', 'pacific saury, comedian',
                            'to touch, to get involved, to be harmful to',
                            'weather, fair weather, turning point', 'fat, deep, daring', 'which way, which one, who',
                            'kanji, feeling, auditor', 'one, for one thing, only', 'skillful, delicious, good',
                            'that way, there, that',
                            'since, request, dependence', 'low, short, deep', 'door, title page, frontispiece',
                            "seven, four o'clock, the seven seas", 'near, close, closely related', 'itchy',
                            'letter, to mail a letter, epistolary style', 'necessary, necessity',
                            'muscle, muscular pain, muscle tissue',
                            'politician, political reform, political process',
                            'newspaper, newspaper company, newsprint',
                            'to miss the mark, to be removed, to be contrary to',
                            'soy sauce, soy sauce dish, soy sauce lees',
                            'small, slight, low', 'to be delighted, to congratulate',
                            'to serve, to be usable, to stick',
                            'lightning, god of thunder, anger', 'takoyaki, 6562 takoyaki, takoyaki pan',
                            'to part, to separate, to lose',
                            'to be broken, to break, to fall through', 'joy, auspicious event, crying for joy',
                            'building, leading actor, leading figure', 'to be surprised, astonishing',
                            'cooking, cuisine, good official',
                            'to be possessed of, to be among', 'the present, as of, present tense',
                            'animal, zoo, doubutsuen',
                            'to harden, to become firm, to gather', 'change, coin return slot',
                            'to begin, to happen, to date', 'lonely',
                            "company, one's workplace", 'cold, cold dark matter, cold war', 'saturday', 'food, eatery',
                            ', head nurse',
                            'younger brother, brother-in-law, pupil', 'drink',
                            'to be disordered, to be discomposed, yearning',
                            'lip, to steal a kiss', 'hiragana', 'sun, ocean, summary',
                            'young person, youth culture, youth subculture',
                            'japanese, japanese language', 'goblin, haunted mansion',
                            'enjoyable, happy memory, joy of learning',
                            'ruler, everyday clothes', 'to surpass', 'airport,', 'living thing, ikimono-gakari',
                            'railroad, rail transport, railroad network', 'early evening', 'envelope, wind and waves',
                            'big, loud, extensive',
                            'brown, light brown, widespread column', 'music, musician, music festival',
                            'daikon, ham actor, dive computer',
                            'to be buried', 'teacher, dying insane, doctrine', 'economy, finance, being economical',
                            'train, palace, country',
                            'heart, guts, construction', 'arithmetic, calculation, dyscalculia',
                            'pencil, pencil sharpener, eastern red cedar',
                            'society, social studies, social science',
                            'younger sister, sister-in-law, younger daughter',
                            'seashell, scale insect, ostracism', 'to get tired, to starve, to be possessed',
                            'airplane, vapor trail, contrail',
                            'head nurse', 'metal, kinzoku, kinh', 'carrot, asian ginseng, man-god',
                            'fruit, fruit store, fruit basket',
                            'mankind, anthropology, anthropologist', 'to be sad',
                            "nine, nine years of age, twelve o'clock",
                            'purple, purple gromwell, soy sauce', 'palm, to flip-flop', 'school, gakkou, fun school',
                            'tailor, clothes hook,',
                            'i, personal, selfishness', 'formal, polynomial, defined style', 'socks, sock, garters',
                            'german, german language',
                            'sad, sad to say', "grey, clark's nutcracker, grizzly bear",
                            'physical education, gymnasium, taiikukan',
                            'to memorize, to learn, to feel', 'government office, translation, post',
                            'good, attractive, small time crooks',
                            'tuesday', 'to go out', 'marriage, bloodstain, marriage ceremony',
                            "teacher, sensei, one's elder",
                            'illness, bad habit, crazy', 'entrance, genkan, intense cold',
                            "happy, joyful, to one's delight",
                            'chicken, chicken meat, henhouse', 'to fall, to be destroyed, to die',
                            'typhoon, wind resistance, gale',
                            'liver, daylily, liquorice', 'to gather', 'human being, character, human',
                            'easy, tender, soft voice',
                            'to teach, to tell, to preach', 'to work, to function, to commit', 'lonely',
                            'contents, internal use, content analysis', 'lawyer, bar association, legal ethics',
                            "overall victory, yūshō, bear's palm", 'siblings, brothers, siblings-in-law', 'if you like',
                            'rest, urgent business, maintaining', 'unrelated', 'prime minister, captain, advocacy',
                            'foreigner, alien, foreign', "the '20s", 'plant, botanical garden, shokubutsuen',
                            'to make sound, to cry, nak',
                            'to raise, to train', 'without change, just like, immediately', 'musicology, music school',
                            'fiance',
                            'to go, to move through, to do', 'business, sales, business hours',
                            'to turn on power, to turn off power',
                            'animal shelter, health department, insurance card', 'akihabara massacre, akihabara@deep',
                            'class, kras, to live',
                            'to take, to have a cramp', 'kitchen, kitchenware, kitchen utensils', 'juui',
                            'may i come in?, please forgive me',
                            'to bend, to turn, to be awry', 'breakfast', 'boy, young man', 'cosmetics, cosmetics store',
                            'mother, wife, you',
                            'export credit', 'section, phrase, verse', 'excuse me, thank you, sorry',
                            'hello, aló presidente',
                            'picture, image, eh?', 'tail, o, cord', 'to be, to have, to be located',
                            'to become, to result in, to consist of',
                            'older sister, young lady, miss', 'post office, postage stamp, mail clerk',
                            'to get dry, to be thirsty, to thirst for', 'kōshien, koushien, koshien stadium',
                            'to face, to go towards, unbeatable', 'beginning, first, origin', 'oyakodon',
                            'information, upper part, multiplication', 'to shave, to cut down, to delete',
                            'to wash, to inquire into, to purify', "still, it's not over yet",
                            'to receive, to contract', 'beautiful',
                            'every day, every single day, mainichi shimbun',
                            'to go to and from, to go to, to circulate',
                            'koto music, having two poles, head office', 'eldest son', 'injury, mistake, fur',
                            'bicycle, runner-up, bicycle trip', 'father, husband, you',
                            'whole life, laugh, one evening', 'thursday',
                            'slowly, easily, well', 'protagonist, head', 'departure, departure time, departure date',
                            'assembly hall, on the sea, opening', 'to go out', 'car, automobile, car accident',
                            'to open, to bloom, to be wide', 'guidebook, guide', 'conference room, conference hall',
                            'factory, elevation, vocal message', 'wonderful, the wonderful o, brave new world',
                            'to teach, to tell, to preach',
                            'copper, bronze, trunk', 'astronaut, space flight, spaceflight',
                            'to run, to rush, to retreat',
                            'to spend, to overdo, to take care of', 'income, source of income, revenue stamp',
                            'your husband, master, your lordship', 'artist, art museum, bijutsukan',
                            'to take, to hang, to come into view',
                            'practice, exercises, practice field', '', 'to request, to call, to entrust to',
                            'cannot help, must not ..., must ...', 'cooperation, powerful, bridge', ', no',
                            'sub-, -ous, asia',
                            'grandfather, grandparent', 'just now', 'thank you', 'refrigerator',
                            'beef, beef noodle soup',
                            'lesson, tuition fee, while in class', 'food', 'to discover, to locate',
                            'doll, puppet, ningyou',
                            'zoo, doubutsuen, zoo hypothesis', 'emergency exit', 'week after next',
                            'parents, conscience, upright',
                            'future, bringing, bringing about', 'to scold, a particular, that kind of',
                            'to loosen, to relax, to reduce',
                            'to get tired, to starve, to be possessed', 'summer vacation', 'to be hit, to touch',
                            'this week, this autumn, this weekend', 'bento', 'to finish, to close, to put away',
                            'lunch',
                            'to go out to meet, to call for, to accept', 'homework, pending issue',
                            'confirmation, to make sure',
                            'study, diligence, experience', 'new, neophilia, new capitalism',
                            'congratulations!, congratulations',
                            'grandmother, old woman, grandmother cell', 'rice field, paddy field, other',
                            'to go by, to run, to go indoors',
                            'to line up, to rival', 'preparation, absolute beauty, exquisite',
                            'preparation, easy, hip measurement',
                            'deed, conduct, asceticism', 'to deliver, to report', 'thing, incident, circumstances',
                            'to appear, to be expressed', 'novel, bar, short pause',
                            'movie theatre, movie theater, movie director',
                            'to compare, to compete', 'to do, to serve as, to wear',
                            'dining room, restaurant, esophagus',
                            'telephone table, telephone bill', 'judo, judo practitioner, judo therapy',
                            'carving, sculpture, overcoming',
                            'to understand, to become clear, i know!', 'splendor', 'to part, to separate, to lose',
                            'to examine',
                            'to be, to have, to be located', 'difficult, impossible, fussy',
                            'interesting, amusing, enjoyable',
                            'walk, strolling, sampo', 'competition, race, racing', 'spanish, spanish language',
                            'choices, selector, chooser',
                            'to laugh, to smile, to sneer', 'washing machine, elective subject',
                            'poem, chinese poem, poetry', 'to choose',
                            'to continue', 'month after next', 'soft, gentle, light', 'thanks for the meal',
                            'to understand, to become clear, i know!', 'salty, calculating, scowling',
                            'stationery, stationery shop',
                            'every week, every fall', 'seventeen, 17 days', 'warm, considerate, warm reception',
                            'inspection, looking up, examination', 'worldwide, world-famous, global scale',
                            'dull, insignificant, absurd',
                            'to come, to be, come', 'monday', 'makeshift', 'simply put', 'friday',
                            'admission, matriculation',
                            'year after next', 'rail bus', 'time and time again, many times, a number of times',
                            'but, regardless of',
                            'business trip, excess of exports, travel expenses', 'japan, two, japanese',
                            'next week, next autumn, coming together', 'ambulance, first-aid, first-aid kit',
                            'limited express, great hurry, high grade', 'please go ahead',
                            'sunflower, himawari, sunflowers',
                            'tree, wood, wooden clappers', 'younger brother', 'to drop, to clean off, to lose',
                            'introduction, inquiry, patrol', 'to memorize, to learn, to feel',
                            'you said, even if, i already told you',
                            'lunch break', 'really, how admirably', 'shinkansen, shinkansen pear',
                            'hospital, hospital ship',
                            'to catch, to grasp, to captivate', 'boy, right mindfulness, true faith', 'fourteen',
                            'to know, to think',
                            'only, flea, drink', 'baby, infant, baby talk',
                            'to reach, to be delivered, to be attentive', "children's day",
                            'to put back, to vomit, to recover', 'spaceship, spaceship earth, astrobiology',
                            'foreign language',
                            'ministry of economy, formula, computer', 'activist, athlete, athletic meet',
                            'repair, end, completion',
                            'participation, oxidation, obstetrics', 'good', "girl, young woman, girls' day",
                            'to collect',
                            'older brother, young man', 'good evening', 'arbitrariness, castanopsis, personal opinion',
                            'to remain',
                            'to sit, to assume, to hold steady', 'toilet', 'welcome home, okaerinasai',
                            'copper, bronze, trunk', 'architect',
                            'wednesday', 'dinner', 'embassy', 'unmanageable, inopportune, disturbing',
                            'municipal office',
                            'order, procedure, pure heart', 'nice to meet you, hajimemashite',
                            'wrong, hopeless, must not do', 'to comfort',
                            'written guarantee', 'do your best, try-hard award',
                            'to miss the mark, to be removed, to be contrary to',
                            'coming of age', 'newsprint, newspaper, newspaper company',
                            'to enter, to join, to be contained',
                            'life expectancy, entropy', 'just like that, that street', 'no good, hopeless, cannot',
                            'sunday',
                            'truth, proper, genuine', 'girl, birthplace, place of rebirth', "that's so",
                            'westernization, western style-house, medlar', 'to move, to operate, to make a move',
                            'last week, selection, specialization', 'younger sister', 'administrator, custodian', '',
                            'care, trouble, good offices', 'coffee shop, kissaten',
                            'to be absent, to rest, to go to bed', 'busy, restless',
                            'document, imperial edict', 'great wall of china', 'input, milk yield, input order',
                            'french, french language',
                            'library, chief librarian', 'salary, hill, rolling hills', 'classroom, department, class',
                            'to say, i agree with you', 'novelist, novelization', 'just right',
                            'to take, to have a cramp', 'company employee',
                            'under construction', 'thanks for the meal', 'sightseeing, sightseer, kenbutsu',
                            'to apologize, to make a mistake, to be wrong', 'to bump into, to encounter, to clash',
                            'to exchange, to replace',
                            'to be, to have, to be located', 'lateness, government', 'guest, customer, customer copy',
                            'marriage ceremony, wedding, wedding hall', 'coming of age', 'still, more, at least',
                            'schedule', 'in use',
                            'store', 'to be lost, to be used up, to disappear',
                            'to be saved, to escape harm, to be helped',
                            'the rabbit, east, rabbit', 'to perform', 'to understand, to become clear, i know!',
                            'real, check mark, re',
                            'to enjoy', 'athletic meet, sports day', 'injury, mistake, fur', '',
                            'salary, hill, rolling hills',
                            'one cup, one drink, full', 'cannot help, must not ..., must ...', 'younger sister',
                            "traveller, travel agent, traveler's diarrhea", 'spaceship, cosmic ray, spaceship earth',
                            'bank employee',
                            "committee member, doctor's office, medical staff", 'week after next',
                            'to live, to finish, to feel at ease',
                            'to be found', 'five, after, go', 'zoo, doubutsuen, zoo hypothesis',
                            'tree, wood, wooden clappers',
                            'income, source of income, revenue stamp', 'foreigner, alien, foreign',
                            'business trip, excess of exports, travel expenses', 'laundry, laundry box',
                            'to install, to, to patronize',
                            'to give up, to elucidate', 'to hold, to possess, to maintain',
                            'worldwide, world-famous, global scale',
                            'korean, korean language, pinus koraiensis', 'cosmetics, cosmetics store',
                            'order, procedure, pure heart',
                            'to tidy up, to settle, to finish', 'trouble', 'safe, certainly, no thanks', 'timetable',
                            'but, regardless of',
                            'driver, chauffeur', 'to hold, to possess, to maintain', 'courier, parcel locker',
                            'birthday, birthday party, happy birthday',
                            'insurance card, ministry of health, insurance papers', 'thank you',
                            'to say, i agree with you', 'to look after, to withhold, to participate in',
                            'origin, basis, cause', 'guidebook',
                            'breakfast, mixing colors, after breakfast', 'emergency exit',
                            'meeting, doubt, explanation',
                            'reservation, contract, programming', 'dairy, milk meter',
                            'terrible, amazing, to a great extent',
                            'to help, to contribute to', 'year-end party, bōnenkai', 'around the world',
                            'trouble, anxiety, crow',
                            'no problem', 'nineteen, therapsids, therapsida', 'fountain pen',
                            'art museum, bijutsukan, art director',
                            'gion festival, gion matsuri', 'overactivity, to overwork', 'medical thermometer',
                            'to collect, to summarize, to establish', 'written guarantee',
                            'preparation, easy, hip measurement',
                            'splendid, sufficient, not needing', 'to transfer, to change', 'protagonist, head',
                            'to be, to have, to be located', 'police officer, police patrol area',
                            'verbal note, note verbale, industrial area', 'to go, to move through, to do',
                            'to assemble, to form', 'thank you',
                            'to that degree', 'to know, to sense, to understand', 'to ask, to hear, to implore',
                            'newspaper company',
                            'safety boots, steel-toe boot', 'to gather', 'shinkansen, shinkansen pear',
                            'old tale, reminiscence',
                            'to begin, to happen, to date', 'graduate school, graduate student', 'weather forecast',
                            'wrong, hopeless, must not do', 'informatics', 'younger brother', 'walk, strolling, sampo',
                            'care, trouble, good offices', 'to do', 'lovely, sixteen candles, very lovely', 'engineer',
                            'perhaps', 'man',
                            'to be in time, to serve', 'tail, slope, cord', 'but, regardless of',
                            'exhibition, art exhibition, show-room',
                            'to make sure', 'woman', 'five, after, go', 'good, sufficient, profitable',
                            'to persevere, to insist that',
                            'nice to meet you, hajimemashite', 'rumour, rumor, gossip',
                            'to understand, to become clear, i know!',
                            'you said, even if, i already told you', 'gymnasium, taiikukan, gym',
                            'participation, oxidation, obstetrics',
                            'museum, hakubutsukan, museology', 'firefighter, fire station, fire engine',
                            'quarrel, brawling, in the prefecture', 'study, diligence, experience',
                            "new year's party, shinnenkai",
                            'only, flea, drink', 'farewell party', 'picture, image, eh?', 'excuse me, thank you, sorry',
                            'unreasonable, impossible, forcible', 'to give', 'just a minute, major general, clear',
                            'come, welcome',
                            'inspection, looking up, examination', 'doer, shite, speculator',
                            'sorting, liquidation, retrenchment',
                            'chinese, chinese language, chinese room', 'to work, to function, to commit',
                            'how, questionable, suspicious',
                            'cleaning, cleanliness, resemblance', 'to gain knowledge, enlightening',
                            'divorce, intelligence, divorce rate',
                            'to move, to inspire, to change', 'thankfully, thanks to your',
                            'telephone call, telephone, telephony',
                            'president, big man, first lady', 'tail, string, cord', 'trainee, training program',
                            'difficulty, accident, fault',
                            'good', 'two, load, burden', 'formal receipt, receipt', 'alarm clock',
                            "i'm sorry, (it's) inexcusable",
                            'washing, relaxing, laundry', 'monk, sangha, to run along', 'good, sufficient, profitable',
                            'broadcasting, packing, legal profession', 'wrong number', 'repair, end, completion',
                            'how, in what way, in what manner', 'greeting, speech, reply', 'study tour',
                            'worry, care, heart and lungs',
                            'discovery, issuing, white key', 'to meet, to be recognized',
                            'leaving hospital, troops, the moon',
                            'post office, mail clerk', 'collaborator', 'calculation, forecast, silicic acid',
                            'study, research, laboratory',
                            'may i ask?', 'meal, diet, typesetting', 'seasoning, condiment',
                            'may i come in?, please forgive me',
                            'to feel exhausted', 'small change', 'exercise, appeal, motion', 'copper, bronze, trunk',
                            'attendance, attendee, student number', 'stomach, medicine, doctor',
                            'export, efferent, exported goods',
                            'surprisingly', 'how are you?', 'great wall of china',
                            'announcement, recital, presentation', 'highway',
                            'translation, deciphering, translator', 'kind, establishing, fresh snow',
                            'savings box, piggy bank',
                            'to say, i agree with you', 'entering, no entry, off-limits',
                            'researcher, kenkyusha, kenkyūsha',
                            'very, that is, apart from that', 'closed today', 'space flight, spaceflight, astronaut',
                            'the west, western world', 'truth, proper, genuine', 'to memorize, to learn, to feel',
                            'slowly, easily, well',
                            'congratulations', 'substitute, stand-in, compensation', 'good, sufficient, profitable',
                            'character, handwriting, the ... word', 'to come, to be',
                            'welding, premature death, outline', 'please',
                            'welcome home', 'leaving early, the whole, on the whole', 'safe, certainly, no thanks',
                            'while in class',
                            'sunflower, himawari, sunflowers', 'welcome', 'invitation, true character, consciousness',
                            'oyakodon',
                            'tail, slope, cord', 'one lump, the same, one letter', 'tail, slope, cord', 'mail order',
                            'life expectancy',
                            'ambulance, emergency blanket', 'invention, intelligent, making sense', 'come, welcome',
                            'practice, exercises, practice field', 'gal, bellboy',
                            'marriage, bloodstain, marriage ceremony',
                            'reserve, declining, forethought', '', 'vending machine',
                            'to hold, to possess, to maintain',
                            'general, ordinary, the same', 'what, you-know-what, whatsit',
                            'seeing, wearing a sword, visitor',
                            'import, afferent, imported goods', 'overall victory, yūshō, brave general',
                            'thanks, kansha, observer',
                            'input process, incoming signal', 'which way, which one, who',
                            'literary prize, literary award, literary girl',
                            'that, part, um ...', 'inspection, sitting out, study', 'overseas student',
                            'pencil sharpener',
                            'alien registration, foreign investor', 'departure, departure time, departure date',
                            'poem, chinese poem, poetry',
                            'poem, chinese poem, poetry', 'adds emphasis, ha', 'kansai airport line',
                            'for a moment, for a while',
                            'tension, tensions, tonus', 'please come', 'to take, to have a cramp',
                            'preparation, absolute beauty, exquisite',
                            'to do over again', 'parking violation',
                            'business trip, excess of exports, travel expenses', 'nhk',
                            'to apply for', 'help, to receive favor, to take care of', 'completion, cheer, sensitivity',
                            'storey, stairs, stage', 'tail, string, cord', 'trouble, anxiety, crow', 'be, is',
                            'to be saved, to escape harm, to be helped', 'weekend carpenter', 'one week', 'to eat',
                            'copper, bronze, trunk',
                            'longevity', 'open', 'goodbye', 'deep-fried chicken, overtime, cruel', 'to give',
                            'arrival, arrival time, station of arrival', 'certainly!',
                            'plan, snowy valley, right ascension', 'parking lot',
                            'to recall', 'please go ahead', 'operation, driving, use', 'engagement, distress, fiance',
                            'production, liquidation, ending', 'hospitalization, in-patient, hospital treatment',
                            'four, forty, four thousand']

wordlist_kata = ['メッ', 'カメ', 'エレ', 'カー', 'ギン', 'カタ', 'ホー', 'キト', 'ベー', 'グラ', 'ルム', 'アレ', 'ガス',
                 'ロッ', 'スー', 'キャ', 'オリ', 'ティ', 'ード', 'カセ', 'チョ', 'タク', 'プー', 'プロ', 'ガラ', 'エン',
                 'ニュ', 'イン', 'シッ', 'コン', 'トラ', 'クリ', 'コッ', 'ジャ', 'ヘル', 'ハイ', 'ダイ', 'ドン', 'ラッ',
                 'フエ', 'サイ', 'チケ', 'スペ', 'セロ', 'キー', 'イド', 'チキ', 'ネッ', 'シー', 'プル', 'ポケ', 'ルス',
                 'テニ', 'ラー', 'クス', 'ウイ', 'バレ', 'アジ', 'テー', 'ンゼ', 'パン', 'スマ', 'ホン', 'スプ', 'バン',
                 'ナス', 'カバ', 'ピュ', 'アパ', 'カレ', 'ブル', 'シャ', 'パリ', 'ロビ', 'ハン', 'ドラ', 'ネク', 'ンコ',
                 'ワー', 'ジル', 'ミー', 'サッ', 'レバ', 'クレ', 'リモ', 'ナム', 'タイ', 'レス', 'トベ', 'ジン', 'ロシ',
                 'スキ', 'ルペ', 'ロサ', 'フル', 'テイ', 'ブラ', 'イギ', 'ズボ', 'モー', 'パー', 'マレ', 'ポス', 'ファ',
                 'コピ', 'ギタ', 'ボタ', 'タワ', 'グル', 'グキ', 'ベト', 'レオ', 'リピ', 'ロー', 'ボー', 'ワイ', 'バナ',
                 'ドア', 'エア', 'シュ', 'ロン', 'ルギ', 'トル', 'ボル', 'クー', 'エス', 'サム', 'バー', 'アル', 'ング',
                 'チー', 'リス', 'レン', 'クッ', 'ソー', 'ペキ', 'サー', 'サン', 'プレ', 'レジ', 'マッ', 'タオ', 'コレ',
                 'マン', 'ホッ', 'ユー', 'モア', 'エッ', 'ソフ', 'ジニ', 'パス', 'コク', 'フォ', 'シコ', 'ビス', 'セー',
                 'ピン', 'トイ', 'ジュ', 'マー', 'ペン', 'メモ', 'スピ', 'イバ', 'スパ', 'ナイ', 'ビザ', 'ジョ', 'キン',
                 'スポ', 'テレ', 'チャ', 'ヨー', 'チリ', 'ベラ', 'ラジ', 'カラ', 'クラ', 'ライ', 'アメ', 'ビル', 'バス',
                 'ミル', 'ポン', 'ポー', 'リー', 'フラ', 'シア', 'ショ', 'イト', 'ゼン', 'メキ', 'ピア', 'サラ', 'スト',
                 'タン', 'シン', 'ニン', 'ボデ', 'アワ', 'ベッ', 'メニ', 'ッシ', 'ロボ', 'ピク', 'ドネ', 'デパ', 'デザ',
                 'カナ', 'ター', 'ガム', 'フィ', 'テン', 'ノー', 'ホテ', 'ドイ', 'ルト', 'タバ', 'バイ', 'マニ', 'ログ',
                 'イガ', 'パッ', 'ラン', 'スイ', 'リカ', 'ビー', 'ヒー', 'メー', 'レポ', 'ダン', 'ムス', 'パチ', 'ゴル',
                 'プテ', 'ニッ', 'ガル', 'ビデ', 'パソ', 'ガー', 'ケー', 'セン', 'ドリ', 'ボラ', 'ペッ', 'カン', 'パイ',
                 'ゴム', 'オケ', 'ステ', 'コー', 'ディ', 'クル', 'スペイ', 'カーテ', 'パソコ', 'アレル', 'ピクニ',
                 'ソフト', 'ヒータ', 'サンプ', 'ソース', 'カタロ', 'グアム', 'クーラ', 'インタ', 'ビール', 'バンド',
                 'ポーラ', 'ストレ', 'ギター', 'マラソ', 'ペンチ', 'ロッカ', 'コーヒ', 'ゴルフ', 'ラジカ', 'ホーム',
                 'ハンガ', 'スケジ', 'テレビ', 'メニュ', 'ワイン', 'ネクタ', 'ピラミ', 'パンフ', 'パスポ', 'ショー',
                 'ヨーク', 'ランプ', 'キトク', 'カード', 'サッカ', 'ノーベ', 'ラジオ', 'ロビー', 'セータ', 'エアメ',
                 'テレホ', 'カバー', 'タオル', 'コース', 'マーク', 'ボール', 'クック', 'ガイド', 'テーブ', 'インド',
                 'ストア', 'チーム', 'ホンコ', 'レート', 'ビート', 'ミルク', 'ステレ', 'ボラン', 'ノック', 'トイレ',
                 'マンシ', 'ロンド', 'メーカ', 'ワープ', 'デート', 'ライン', 'センタ', 'エリー', 'スポー', 'ヨーロ',
                 'ルエン', 'リモコ', 'カセッ', 'クリー', 'ホテル', 'キャプ', 'ミキサ', 'フォー', 'サラリ', 'ドリル',
                 'ブラジ', 'コンピ', 'ベルト', 'ラーメ', 'タイプ', 'クラシ', 'ドライ', 'アメリ', 'イギリ', 'パチン',
                 'シャン', 'ガスレ', 'メート', 'ウイス', 'レータ', 'ベトナ', 'チェッ', 'ハイキ', 'スイッ', 'シンガ',
                 'ポール', 'レスト', 'マニュ', 'ビデオ', 'インフ', 'サービ', 'タワー', 'ベート', 'クラス', 'チャン',
                 'シャワ', 'カリフ', 'ホルモ', 'アクセ', 'シング', 'ペンキ', 'コピー', 'ミーテ', 'ハンバ', 'スーパ',
                 'センチ', 'シャツ', 'ピンポ', 'ボディ', 'サーカ', 'コンテ', 'タバコ', 'キーワ', 'デザイ', 'ポスタ',
                 'ニュー', 'スピー', 'セット', 'チケッ', 'ジュー', 'オート', 'スキー', 'シャー', 'テープ', 'ファッ',
                 'マッチ', 'サイズ', 'エアコ', 'ジョギ', 'カタカ', 'メキシ', 'タント', 'アジア', 'タンカ', 'ドイツ',
                 'ダンス', 'ハンサ', 'ピック', 'グラム', 'グラス', 'カメラ', 'ユーモ', 'メール', 'レバー', 'レコー',
                 'ドラマ', 'ベッド', 'エレベ', 'セロテ', 'ヘルメ', 'コップ', 'カラオ', 'トボタ', 'ズボン', 'フィリ',
                 'ジャパ', 'ペキン', 'カンガ', 'エンジ', 'バレー', 'プレゼ', 'タイヤ', 'システ', 'コート', 'フロン',
                 'ダイニ', 'ガラス', 'ラッシ', 'ロシア', 'キャッ', 'ハンカ', 'パッキ', 'センス', 'レポー', 'ボタン',
                 'ペット', 'ロボッ', 'ジャズ', 'フラン', 'スプー', 'フラッ', 'ピアノ', 'レット', 'プール', 'チリソ',
                 'クリス', 'カレン', 'グルー', 'ホッチ', 'ボルト', 'タイマ', 'ケーキ', 'バンコ', 'ツクラ', 'チャレ',
                 'コイン', 'スパナ', 'ポケッ', 'アルバ', 'ファイ', 'シート', 'エスカ', 'インス', 'シーデ', 'クレー',
                 'ノート', 'テニス', 'ハンマ', 'ダイエ', 'アパー', 'デパー', 'バナナ', 'ティア', 'スーツ', 'パーテ',
                 'チョコ', 'ガソリ', 'スター', 'ローン', 'カップ', 'レジャ', 'プレイ', 'パーセ', 'シリン', 'ニーズ',
                 'タクシ', 'ボーナ', 'ライタ', 'データ', 'ロサン', 'フィル', 'シュカ', 'コスト', 'アワー', 'トラッ',
                 'マレー', 'モータ', 'ナイフ', 'ステイ', 'オリン', 'ローマ', 'パトカ', 'パイプ', 'コンサ', 'プログ',
                 'ミュン', 'ファク', 'イラン', 'バック', 'ベラク', 'ポスト', 'ボート', 'キャン', 'カーテン', 'ジョギン',
                 'シャンプ', 'ピラミッ', 'キャプテ', 'モーター', 'エアメー', 'ホッチキ', 'サッカー', 'ポスター',
                 'オートバ', 'ホームス', 'ウイスキ', 'サンプル', 'ショート', 'ハンカチ', 'パスポー', 'リモコン',
                 'ニュース', 'チリソー', 'メニュー', 'ロボット', 'フランケ', 'スプーン', 'オリンピ', 'ロッカー',
                 'エスカレ', 'スーパー', 'レジャー', 'ダイエッ', 'ファック', 'アクセス', 'ハンサム', 'フラッシ',
                 'マンショ', 'ノーベル', 'ベートー', 'サラリー', 'パーティ', 'ロンドン', 'カレンダ', 'キャンセ',
                 'ミュンヘ', 'エンジニ', 'ピクニッ', 'サービス', 'ヒーター', 'パッキン', 'シャープ', 'キャッシ',
                 'ハンマー', 'カタログ', 'コインロ', 'ファイル', 'ヘルメッ', 'プレゼン', 'プログラ', 'フィルム',
                 'ラッシュ', 'ネクタイ', 'メートル', 'シンガポ', 'レポート', 'ホルモン', 'マニュア', 'カリフォ',
                 'ファクス', 'テレホン', 'バンコク', 'カセット', 'コンピュ', 'アルバイ', 'レストラ', 'ボディー',
                 'ハンガー', 'スポーツ', 'コンテス', 'グループ', 'チェック', 'ハンバー', 'アメリカ', 'インドネ',
                 'ジュース', 'チャレン', 'ユーモア', 'チケット', 'ダイニン', 'ベトナム', 'スペイン', 'システム',
                 'カタカナ', 'ハイキン', 'ホンコン', 'セーター', 'ビートル', 'パソコン', 'メキシコ', 'フロント',
                 'テープレ', 'コーヒー', 'インスタ', 'タイマー', 'フォーク', 'ヨーロッ', 'カラオケ', 'ニューヨ',
                 'スケジュ', 'タクシー', 'アルバム', 'ミキサー', 'エアコン', 'インフル', 'パンフレ', 'マレーシ',
                 'エンジン', 'セロテー', 'フランス', 'ロサンゼ', 'タンカー', 'マラソン', 'シーディ', 'プレイガ',
                 'クリーニ', 'エレベー', 'ライター', 'ボーナス', 'ワープロ', 'スピーチ', 'ガソリン', 'ベラクル',
                 'ボランテ', 'デザイン', 'ドライブ', 'デパート', 'パーセン', 'ストレス', 'ジャパン', 'シングル',
                 'ピンポン', 'ドライバ', 'キーワー', 'フィリピ', 'カンガル', 'パトカー', 'クリスマ', 'スイッチ',
                 'クーラー', 'シートベ', 'ステレオ', 'スピード', 'センター', 'バレーボ', 'クレーン', 'ミーティ',
                 'スタート', 'ポーラン', 'バンドン', 'ファイト', 'イギリス', 'アレルギ', 'インター', 'エリーゼ',
                 'メーカー', 'シリンダ', 'サーカス', 'チャンス', 'トラック', 'ポケット', 'ボールペ', 'チョコレ',
                 'クラシッ', 'コンサー', 'テーブル', 'ブラジル', 'パチンコ', 'アパート', 'ガスレン', 'シャワー',
                 'カップラ', 'レストラン', 'ホームステ', 'インターネ', 'ファックス', 'ビートルズ', 'エレベータ',
                 'ドライバー', 'インフルエ', 'シーディー', 'カリフォル', 'ポーランド', 'チャレンジ', 'クリーニン',
                 'テープレコ', 'ホッチキス', 'オートバイ', 'プレゼント', 'ガスレンジ', 'フラッシュ', 'バレーボー',
                 'カンガルー', 'フィリピン', 'クリスマス', 'サラリーマ', 'ベラクルス', 'チョコレー', 'マンション',
                 'コンピュー', 'シリンダー', 'パッキング', 'スケジュー', 'チリソース', 'スポーツク', 'パスポート',
                 'アレルギー', 'ダイニング', 'カレンダー', 'オリンピッ', 'エスカレー', 'プログラム', 'プレイガイ',
                 'キーワード', 'パーティー', 'パンフレッ', 'ピクニック', 'インドネシ', 'マニュアル', 'シンガポー',
                 'ヘルメット', 'パーセント', 'カップラー', 'ハイキング', 'ボールペン', 'ダイエット', 'アルバイト',
                 'フランケン', 'ボランティ', 'ミーティン', 'ピラミッド', 'シャンプー', 'ハンバーグ', 'ロサンゼル',
                 'シャープペ', 'コンテスト', 'ミュンヘン', 'エアメール', 'コインロッ', 'ヨーロッパ', 'クラシック',
                 'ジョギング', 'カセットテ', 'シートベル', 'ウイスキー', 'エンジニア', 'キャッシュ', 'ニューヨー',
                 'キャプテン', 'インスタン', 'テレホンカ', 'ベートーベ', 'キャンセル', 'セロテープ', 'コンサート',
                 'スタートボ', 'マレーシア', 'インターネッ', 'サラリーマン', 'コインロッカ', 'スケジュール',
                 'カセットテー', 'クリーニング', 'シャープペン', 'シートベルト', 'シンガポール', 'カリフォルニ',
                 'ホームステイ', 'スタートボタ', 'テープレコー', 'キャッシュカ', 'インスタント', 'プレイガイド',
                 'バレーボール', 'インドネシア', 'ボランティア', 'チョコレート', 'ニューヨーク', 'コンピュータ',
                 'オリンピック', 'エスカレータ', 'カップラーメ', 'テレホンカー', 'パンフレット', 'パーティール',
                 'ベートーベン', 'スポーツクラ', 'ミーティング', 'エレベーター', 'ロサンゼルス', 'インフルエン',
                 'ダイニングキ', 'キャッシュカー', 'テープレコーダ', 'カップラーメン', 'テレホンカード',
                 'カセットテープ', 'ダイニングキッ', 'スポーツクラブ', 'カリフォルニア', 'コンピューター',
                 'コインロッカー', 'インフルエンザ', 'シャープペンシ', 'パーティールー', 'インターネット',
                 'エスカレーター', 'インスタントラ', 'スタートボタン']

wordlist_kata_translated = ['no!, me, message', 'tortoise, heavy drinker, turtle crest',
                            'elevator, electronics, electric guitar', 'car, kerr, curtain',
                            'pine grosbeak, tidepool gunnel, pholidae', 'prattle, katakana, snail',
                            'discarded tiles, oh, hoo', 'quito, 10793 quito, yellow darter', 'bleh, bex, b',
                            'graphics, gram, graph', 'rumtopf, râmnicu vâlcea, lumumba', 'that, that person, then',
                            'gas, poison gas, dense fog', 'locker, rocker, rod', 'sioux, sou, si',
                            'camera, camp, camping', 'orientation, original, unique', 'tea, tee, team',
                            'window, extent, limit', 'cassette, game cartridge, cassette tape',
                            'a little, just a minute, somewhat', 'taxi, taxicab, taximeter',
                            'toot, honk, farting sound', 'professional, program, project', 'gala, glass, junk',
                            'pencil, engine, engineer', 'news, nuance, new zealand', 'in, enter here, back nine',
                            'chic, sick, six nines', 'gong, kon, computer', 'tiger, drunkard, trouble',
                            'clitoris, japanese chestnut, christmas', 'stealthily, cook, tap',
                            'jam, fruit preserves, journalist', 'hell, mr, hel', 'high, al-hayy, hiking',
                            'diamond, diamonds, dial', 'don, dong, bang', 'rush hour, rack, lacq', 'hue, huế',
                            'psi, rhinoceros, siren', 'ticket, chikenshi, cost of a ticket',
                            'insert a space, space, spain', 'cello, cellophane tape, sellotape', 'key, chi, screech',
                            'id, idol, ido', 'chicken, coward, chicken soup', 'necklace, network, internet',
                            'c, celsius, cyan', 'pull, plutonium, snowplow turn', 'poke, pocket, pager',
                            'rustenburg, rusutsu resort, ruslan olikhver', 'tennis, tennis court, tennis elbow',
                            'laa, ra, ramen', 'camphor tree, medicine,', 'yes, huy, whisky',
                            'barrel, baler, volleyball', 'agitation, carangidae, horse mackerel',
                            'table, tape, tape recorder', 'nzérékoré, nzérékoré region', 'bread, staff of life, pan-',
                            'smart, slim, skilful', 'phon, fon, truth', 'spoon, spray, sprayer', 'bun, van, bang',
                            'eggplant, nasubi, solanaceae', 'cava, cover, covering', 'puma, cougar, pure',
                            'apartment, apartheid', 'calendar, calender, curry', 'bull, bulldog, bulldozer',
                            'shirt, shower, champagne', 'paris, pacific league, pharisee', 'lobby, lobbyist, robin',
                            'khan, haan, han', 'dora, gong, drama', 'tie, necktie, dark-natured',
                            "nkongsamba, n'ko alphabet", 'word processor, world series, word', 'gill, zil, zircaloy',
                            'me, meeting, medium', 'quickly, indifferently, soccer team', 'liver, reverse, rebirth',
                            'crane, credit card, credit', 'remote control, remote, remote sensing',
                            'south korea, namco, namul', 'thailand, tie, sea bream', 'reply, -less, sexless',
                            'pittosporaceae, pittosporum', 'zine, gin, jinn', 'russia, russian, russian language',
                            'skiing, ski, sukiyaki', 'lupercalia, ruperto chapí, lupeni', 'los angeles, rosario',
                            'full, flute, fruit', 'tailor, takeout, take-out', 'bra, bula, blouse',
                            'united kingdom, england, british person', 'trousers, trouser press, sloppy',
                            'mho, meaux, motor', 'paper, foolishness, par', 'malé, malaysia, visitor from afar',
                            'point of sale, postbox, post', 'fa, f, zip fastener', 'copy, book jacket blurb, copier',
                            'guitar, guitarist, guitar solo', 'button, push-button, dripping',
                            'tower, scrubbing brush, tower records', 'guru, accomplice, group',
                            'throbbing pain, jerkily', 'vietnam, viet nam, sticky', 'leo, leotard, leopon',
                            'repeater, repeat customer, repeating', 'rho, low, low gear', 'bow, bow tie, bo',
                            'y, yellow, short grain', 'banana, banner, web banner', 'door, total idiot, doorman',
                            'air, ayr, area', 'cream puff, profiterole, simulation', 'sakae, london, long dress',
                            'lugia', 'torr, delete, turkey', 'volt, bohrt, bolt', 'air conditioner, cooler, cuba',
                            's, south, sulfur', 'sum, sam, polyergus samurai', 'bar, crossbar, wah', 'two, be, alcohol',
                            'ngounié province', 'seven, scissors, team', 'fracture, lithograph, squirrel',
                            'brick, lens, rental car', 'clearly, cookie, cook', 'soda, sausage, sauce',
                            'beijing, beijing dialect, peking duck', 'sir, service, discount', 'three, sun, san',
                            'pre-, present, play', 'checkout, rezh, leisure', 'match, matsutake, sperm whale',
                            'towel, terrycloth, yami people', 'collection, collecting, cholera', 'man, mann, cartoon',
                            'deeply, polar bear, hot', 'you, hjo, u', 'moa, moire, moire pattern',
                            'eiffel tower, essay, x-ray', 'soft, software, soft hat',
                            'gini coefficient, zinnia, gignod', 'passing, pass, path', 'severe, richness, cocktail',
                            'forward, forwarding, folk song', 'japanese anchovy, princess-flower, tibouchina',
                            'screw, bis-, cookie', 'sweater, sale, saving', 'pin, first, rake-off',
                            'toy, toilet, toilet paper', 'carpet, juice, soft drink', 'mahjong, market, marquette',
                            'pen, paint, pension', 'note, memory, memori', 'speaker, loudspeaker, speech',
                            'iba, thorny shrub, wild rose', 'spa, spaghetti, span', 'knife, nylon, game under lights',
                            'visa, visa inc., bizarre', 'jogging, joke, joker', 'goldfish, blond hair, blond',
                            'sport, sports car, spot', 'tele, terret, television', 'chance, chime, channel',
                            'europe, yogurt, yorkshire pudding', 'chile, squares, scattering',
                            'wrasse, balcony, veranda', 'radio, radium, radio station', 'emptiness, dishonoured, sky',
                            'class, kras, club', 'lie, lai, raï', 'american, america, united states',
                            'bill, billboard, burma', 'bus, bath, bass', 'mil, mill, mil-réis',
                            'methamphetamine, pon, pat', 'pau, porter, pole', 'leadership, league, reading',
                            'hula, fry pan, frying pan', 'shear, shea tree, sheer', 'shock, crisis, show',
                            'itoyo, african pompano', 'gentleman, osmunda japonica, zenrin',
                            'mexico, remarkably, gulf of mexico', 'peer, piano, pianist', 'salary, salaryman, sarah',
                            'strike, kitchen stove, stop', 'tongue, thann, tan', 'thin, shin, syn-',
                            'carrot, asian ginseng, garlic', 'body, body blow, bodyguard',
                            'foxtail millet, abalone, hour', 'bed, commuter town, bedmaking',
                            'menu, schedule, menu bar', 'be', 'robotics, robot, robot car', 'picnic, outing, picture',
                            'doner kebab, donation, donets', 'department store, department, departure',
                            'design, dessert, desert', 'hammer, hopeless swimmer, canary', 'terminal, tar, turbine',
                            'chewing gum, gum, guam', 'film, philippines, finland', '10, japanese marten, marten',
                            'no, notebook, note', 'hotel, fairy slipper, hotel prostitution',
                            'germany, german, german language', 'rutog county, 2518 rutllant, rutger hauer',
                            'taba, tobacco, tobacco plant', 'bye, bay, bisexual',
                            'manila, operations manual, user guide', 'log, logarithm, login',
                            'tinea translucens, paralomis histrix', 'poof, package, passion',
                            'run, orchid, netherlands', 'lightly, watermelon, switch',
                            'recovery, african wild dog, lycaon pictus', 'b, bee, beer', 'hero, heater, heat island',
                            'baa, me, metre', 'report, reportage, reporter', 'done, just done, dance',
                            'mustang, mustang horse, muslim', 'snapping, pachinko, pati', 'golf, golfer, golf course',
                            'pteranodon, petit verdot, petit manseng', 'sweetly, nickel, nickname',
                            'gal, bellboy, garzon', 'bidet, douche, video',
                            'personal, personal computer, computer shop', 'gar, guardrail, guard rail',
                            'k, kilo-, kelvin', 'stopper, sen, centimeter', 'durian, dorian, drink',
                            'bora, striped mullet, redlip mullet', 'phooey, pet, trumpet', 'can, canned food, tin can',
                            'pie, palmier, tile', 'gum, eraser, condom', 'orchestra, mole cricket, being penniless',
                            'lovely, stereo, steak', 'caux, pays de caux, coffee', 'day, daytime, d',
                            'car, wheel, walnut', 'spain, spanish, spanish language', 'curtain, curtain call, curtsy',
                            'personal computer, computer shop', 'allele, allergy, aversion',
                            'picnic, outing, picnic table', 'soft, software, soft hat', 'heater',
                            'sample, display model, sampling', 'sauce, source, source program',
                            'catalog, catalog retailing, catalog spec', 'guam, uss guam, guam rail',
                            'air conditioner, cooler, coolant', 'interchange, international, interview',
                            'beer, biel, bia', 'band, belt, band aid', 'polar, paula, poland',
                            'stress, straight, straightforward', 'guitar, guitarist, guitar solo',
                            'marathon, malathion, marathon race', 'cutting pliers, pliers',
                            'locker, rocker, locker room', 'coffee, coffee cup, coffee shop',
                            'golf, golfer, golf course', 'radical, radicalist, radicalism', 'platform, home, home base',
                            'hunger, hungary, hungarian dances', 'schedule, diary, scheduling',
                            'television, tv program, television program', 'menu, schedule, menu bar',
                            'wine, wine glass, wine red', 'tie, necktie, nectar', 'pyramid, pyramidon, pyramid selling',
                            'pamphlet, brochure, pan-focus', 'passport, passport to paris, passport card',
                            'show, tv show, she', 'yoke, york, yorkshire pudding', 'lamp, ramp, rump',
                            'vested, praiseworthy, strange', 'card, credit card, match',
                            'soccer team, soccer player, soccer ball', 'nobel prize, nobel, nobel peace prize',
                            'radio, radio station, radio dj', 'lobby, lobbying, robbie keane', 'sweater, setthathirath',
                            'airmail', 'telephone card, telephone, telephone service', 'cover, covering, coverage',
                            'towel, terrycloth, towel rack', 'course, lane, full-course meal',
                            'mark, to mark, trademark', 'ball, bowl, board', 'cook, 3061 cook, cook islands',
                            'guide, guidebook, guide pin screw', 'table, tablecloth, table manners',
                            'india, indonesia, indochina', 'store, storing, stoa', 'team, teamwork, team play',
                            'hong kong, hong kong dollar, hong konger', 'rate, late, rating', 'beet, beat, kick',
                            'milk, infant formula, condensed milk', 'stelle, stereo, stereotype',
                            'borane, volunteer, volunteering', 'knock, fungo hitting, tap',
                            'toilet, toilet paper, toiletry', 'condominium, munsingwear, munshingwear',
                            'ronde, rondo, london', 'manufacturer, maker, name-brand item',
                            'warp, warp drive, word processor', 'date, dating, date rape', 'line, linka, rhine',
                            'centre, center fielder, senta', '616 elly, elite, elitism', 'sport, sports car, sportsman',
                            'europe, european, european mole', 'ruen', 'remote control, virtual channel',
                            'cassette, game cartridge, cassette tape', 'cree, coolie, cream',
                            'hotel, hotel restaurant, hotel worker', 'captain, captcha, caption',
                            'mixer, mixer tile, blender', 'pho, four, foix', 'office worker, salaryman, salary',
                            'drill bit, drill, drill down', 'brazil, bra, brassiere',
                            'computer, computer game, pc game', 'belt, drive belt, belting',
                            'ramen, lamian, rigid frame', 'type, typewriter, typing',
                            'classical music, classic, classic car', 'dry, drive, to',
                            'america, united states, american', 'united kingdom, england, british person',
                            'with a click, ornamental clip, pachinko', 'beautiful, champagne, shanghai',
                            'gas cooker, gas laser', 'mate, metre, meter', 'whisky, whisker, whisper',
                            'laeta kalogridis', 'vietnam, viet nam, vietnam airlines', 'tsk, chirp, check',
                            'hiking, hiking trail, high kick', 'switch, switch-hitter, switch hitter',
                            'singapore, singer, singer-songwriter', 'pole, poll, pol', 'rest, restaurant, restoration',
                            'operations manual, user guide, manicure', 'video, video tape, video camera',
                            'inflation, information, influenza', 'service, discount, free service',
                            'tower, tower records, comrade', 'beethoven, betong district, 937 bethgea',
                            'class, kras, classmate', 'asphalt, chance, channel', 'shower, shower stall, shower gel',
                            'caliph, california', 'hormone, hormone therapy, horumonyaki',
                            'accessory, accent, intonation', 'singles, single people, single room',
                            'paint, painting, painter', 'copy, book jacket blurb, copier',
                            'meeting, meeting room, meteor', 'sales, hamburger, hamburg steak',
                            'supermarket, subtitles, superheterodyne', 'centimeter, centi-, sentimental',
                            'shirt, shirt collar, shirt blouse', 'ping-pong, pinpoint, ding-dong dash',
                            'body, body blow, bodyguard', 'circus, circumflex, circadian rhythm',
                            'storyboard, conté, comté', 'tobacco, tobacco plant, tabaco',
                            'key word, keyword, index term', 'design, designer, designer drug',
                            'poster, poster color, poster value', 'new, nu, gnu', 'speaker, loudspeaker, speech',
                            'set, setting up, setting', 'ticket, ticket reseller, ticket counter', 'jew, jus, carpet',
                            'auto, oat, motorcycle', 'skiing, ski, skier', 'whoosh, hiss, sizzle',
                            'tape, tape recorder, tape library', 'fax, fax machine, fashion',
                            'match, matching, matchbox', 'size, uss sides, increase in size',
                            'air conditioner, air compressor, air conditioning',
                            'jogging, jogging shoes, jogging pants', 'katakana, clattering, katakana word',
                            'mexico, gulf of mexico, mexican', 'tanto, tantra, tantrix', 'asia, asian countries, asian',
                            'thangka, tanker, to speak sharply', 'germany, german, german language',
                            'dance, dance party, dance club', 'hamsa, handsome, strong', 'pick, ice pick, pickaxe',
                            'gram, gram stain, gram staining', 'glass, glasses, grass',
                            'camera, photographer, cameraman', 'humor, humour, humorous', 'email, mail, message',
                            'liver, lever, joystick', 'record, gramophone record, recorder', 'drama, dhrama, drummer',
                            'bed, commuter town, bedmaking', 'elevation, elevator, elevator operator',
                            'cellophane tape', 'helmet, hermes, herma', 'glass, cups, kopf',
                            'karaoke, karaoke club, karaoke bar', 'to fly, to jump, to spatter',
                            'trousers, long johns, trouser press', 'philippines, filipino, philip',
                            'japan, japan cup, japanese', 'beijing, beijing dialect, peking duck', 'kanga, kangaroo',
                            'engine, engineer, enjoying', 'volleyball, barré, valley',
                            'present, presentation, presence', 'tire, snow chains, tire roller',
                            'system, system v, systems', 'coat, coating, court', 'fluorocarbon, front, reception',
                            'dining, dining room, meal', 'glass, glazing, transparency', 'rush hour, rush, rush print',
                            'russia, russian, russian language', 'yikes!, ook, customer',
                            'handkerchief, handkerchief tree, dove tree', 'packing, packing-case, packing-paper',
                            'taste, tasteful, sense of wonder', 'report, reportage, reporter',
                            'button, push-button, tree peony', 'pet, trumpet', 'robot, robotics, robot car',
                            'jazz, jazz dance, jazz club', 'franc, flan, furan', 'spoon, sputnik v, spooling',
                            'flat, flash, newsflash', 'piano, piano recital, piano wire',
                            'let, rett syndrome, let it be', 'pool, pooling, poole', 'chili sauce, hot sauce',
                            'christmas, christ, christmas tree', 'calendar, calender, currency', 'glue, grue, group',
                            'stapler, staple', 'volt, bohrt, bolt', 'timer, stopwatch, time keeper',
                            'cake, cake making, cake shop', 'bangkok, vancomycin', 'to make, to prepare, to raise',
                            'taking on, challenge, challenger', 'coin, token, laundromat', 'spanner, spanaway',
                            'pocket, pager, pocket-size', 'alvar, alba, aruba', 'phi, diameter symbol, file',
                            'seat, sheet, spreadsheet', 'escalator, escalation,', 'ins, insulin, instant',
                            'cd player, compact disk, cash dispenser', 'clay, cray, crane', 'notebook, note, laptop',
                            'tennis, tennis court, tennis elbow', 'hammer, hammer beam truss, hammer beam',
                            'diet, losing weight, dieting', 'apartment, apartment house, aperture grille',
                            'department store, department, departure', 'banana, banana republic', 'tier, tear, tiara',
                            'suit, suitcase, stunt man', 'party, party dress, partition',
                            'chocolate, choco, chocolate cake', 'gasoline, gas station, filling station',
                            'star, star symbol, start', 'loan, rhoon, lawn', 'cup, couple, cupcake',
                            'leisure, leisure industry, leisure center', 'play, performance, praying',
                            'percent, percentage, perceptron', 'cylinder lock, cylinder, syringe',
                            'needs, need, níðhöggr', 'taksi, taxi, taxicab', 'bonus, bonus stage, loan',
                            'lighter, writer, leitha', 'data, database, data link', 'los angeles, uss los angeles',
                            'philharmonic, fill, film', "wine shop, employer's house, subjectivity",
                            'cost, high cost, cost performance', 'hour, award, auerbach', 'truck, trap, trappes',
                            'malaya, malay, malaysia', 'motor, motor show, auto show', 'knife, knifefish, notopteridae',
                            'stay, stained glass, state', 'olympics, olympic event, olympic sports',
                            'rome, roma, latin alphabet', 'patrol car, t. j. hooker', 'pipe, channels, tobacco pipe',
                            'concert, consultant, concert hall', 'program, programmer',
                            'munich, munchen, beer hall putsch', 'fax, fax machine, facsimile',
                            'iran, castor oil plant, eland', 'back, background, backing',
                            'vera cruz, veracruz, siege of veracruz', 'postbox, post, post-',
                            'boat, boat people, boat neck', 'yelp, sales campaign, kiang',
                            'curtain, curtain wall, curtain call', 'jogging, jogging shoes, jogging pants',
                            'shampoo, lake champlain, champlain', 'pyramid, pyramid selling, pyramid-style',
                            'captain, captain jacket, captain canuck', 'motor, motor show, auto show', 'airmail',
                            'stapler, staple', 'soccer, sacker, bagging', 'poster, poster session, poster value',
                            'motorcycle, autobiography, autobacks', 'homestay, home schooling, homeschooling',
                            'whisky, whisky sour, whisky bonbon', 'sample, display model, sample return',
                            'short, shortstop, short hair', 'handkerchief, handkerchief tree, dove tree',
                            'passport, passport to paris, passport card', 'remote control, virtual channel',
                            'news, newscaster, news presenter', 'chili sauce, hot sauce', 'menu, schedule, menu bar',
                            'robot, robotics, robot car', 'frankenstein, franken', 'spoon, spoon sports, spoon bending',
                            'olympics, olympic event, olympic sports', 'locker, rocker, locker room',
                            'escalator, escalation', 'supermarket, subtitles, superheterodyne',
                            'leisure, leisure industry, leisure market', 'diet, losing weight, dieting',
                            'fuck, fax, fax machine', 'access, web counter, access control',
                            'handsome, strong, hansom cab', 'flash, newsflash, flash rom',
                            'condominium, salon, mansion house', 'nobel, nobel prize, nobel peace prize',
                            'beethoven, 1815 beethoven, beethoven virus', 'salary, office worker, salaryman',
                            'party, party dress, particle board', 'london, hms london, london university',
                            'calendar, calender, calendar clock', 'cancellation, cancellation charge, canceller',
                            'munich, munchen, munich conference', 'engineer, engineering, engineering plastic',
                            'picnic, outing, picnic table', 'service, discount, free service', 'heater',
                            'packing, packing-case, packing-paper', 'sharp, number sign, mechanical pencil',
                            'cash card, atm card, cache', 'hammer, hammah, hammer beam truss',
                            'catalog, catalog spec, catalog set', 'coin locker babies', 'file, file name, filename',
                            'helmet, stahlhelm, motorcycle helmet', 'presentation, present',
                            'program, programmer, programming', 'film, film sensitivity, film badge',
                            'rush, rush hour, rush print', 'tie, necktie, necktie pin', 'metre, meter, rice',
                            'singapore, singapore airlines, singapore telecom', 'report, reportage, reporting line',
                            'hormone, horumonyaki, hormone therapy', 'operations manual, user guide, manual focus',
                            'california', 'fax, fax machine, fax transmission',
                            'telephone, telephone card, telephone box', 'bangkok, bangkok post, bangkok glass f.c.',
                            'cassette, game cartridge, cassette tape', 'computer, computer game, pc game',
                            'part-time job, part-time worker, albite', 'restaurant, dinner theater, food mall',
                            'body, body blow, bodyguard', ', hunger, hangar', 'sport, sports car, sportsman',
                            'contest, contesting', 'group, rock band, group home', 'check, checking, check-in',
                            'hms humber, humber, hamburger', 'america, united states, american',
                            'indonesia, indonesian', 'juice, soft drink, deuce', 'taking on, challenge, challenger',
                            'humor, humour, sense of humor', 'ticket, ticket reseller, ticket counter',
                            'dynein, dining, dining room', 'vietnam, viet nam, vietnam airlines',
                            'spain, spanish, spanish language', 'system, system v, systems', 'katakana, katakana word',
                            'hiking, hiking trail', 'hong kong, hong kong dollar, hong konger',
                            'sweater, setthathirath', 'beetle, beatles, the beatles',
                            'personal computer, computer shop', 'mexico, gulf of mexico, mexican',
                            'front, reception, front office', 'tape recorder', 'coffee, coffee cup, coffee shop',
                            'instagram, instant, instant ramen', 'timer, stopwatch, time keeper',
                            'fork, forkball, folk', 'europe, european, european mole',
                            'karaoke, karaoke club, karaoke bar', 'new york, new yorker', 'schedule, diary, scheduling',
                            'taxi, taxicab, taximeter', 'album, photograph album, the album leaf', 'mixer, blender',
                            'air conditioner, air compressor, air conditioning', 'influenza, influence',
                            'brochure, pamphlet', 'malaysia, malaysia airlines, malaysian person',
                            'engine, engine brake, engine braking', 'cellophane tape',
                            'france, french, french language', 'los angeles, death wish ii', 'tanker, tankard',
                            'marathon, malathion, marathon race', 'cd player, compact disk, cash dispenser',
                            'playgirl, ticket agency', 'cleaning, laundry',
                            'elevator, elevator operator, elevator landing', 'lighter, writer',
                            'bonus, bonus stage, loan', 'word processor', 'speech, speech contest, speech therapy',
                            'gasoline, gas station, filling station', 'vera cruz, veracruz, siege of veracruz',
                            'volunteer, volunteering', 'design, design policy, cold perm', 'drive, to, to drive',
                            'department store, department, department h', 'percent, percentage, percent sign',
                            'stress, stress test, stress testing', 'japan, japan cup',
                            'single, single bed, single-breasted', 'ping-pong, ding-dong, doorbell',
                            'driver, screwdriver, driver stack', 'key word, keyword, index term',
                            'philippines, filipino, philippine airlines', 'kangaroo, kangaroo care',
                            'patrol car, t. j. hooker', 'christmas, christmas tree, christmas eve',
                            'switch, switching hub', 'air conditioner, cooler, cooler box', 'seat belt, seatbelt sign',
                            'stereo, stereotype, stereo camera', 'speed, speeding up, speedometer',
                            'centre, center fielder, senta', 'volleyball', 'crane, claw crane, crane truck',
                            'meeting, meeting room, meteor', 'start, starting, to make a start',
                            'poland, polish, polish language', 'bandung', 'fight, fighting spirit, fight!',
                            'united kingdom, england, great britain', 'allergy, aversion, allergic rhinitis',
                            'interchange, international, interview', 'elise, für elise',
                            'manufacturer, maker, name-brand item', 'cylinder, cylinder lock, cylinder oil',
                            'circus, the circus, circus polka', 'chance, being there, opportunity loss',
                            'truck, track, track event', 'pocket, pager, pocket-size', 'ball-point pen, ballpoint pen',
                            'chocolate, chocolate cake, chocolate fountain', 'classical music, classic, classic car',
                            'concert, concert hall, concert master', 'table, tablecloth, table manners',
                            'brazil, banco do brasil', 'pachinko, slingshot, pistol',
                            'apartment, aparthotel, apartment house', 'gas cooker',
                            'shower, to take a shower, bidet toilet', 'coupler, cup noodles',
                            'restaurant, dinner theater, food mall', 'homestay, home staging, homestead',
                            'internet, internet site, internet television', 'fax, fax machine, fax number',
                            'beatles, the beatles, 8749 beatles', 'elevator, elevator operator, elevator landing',
                            'driver, screwdriver, driverless car', 'influenza, influence, influenza virus',
                            'compact disk, cash dispenser, cd player', 'california', 'poland, polish, polish language',
                            'taking on, challenge', 'cleaning, laundry', 'tape recorder', 'stapler, staple',
                            'motorcycle, autobiography, motorcycle race', 'present, love me', 'gas cooker',
                            'flash, newsflash, flush', 'volleyball', 'kangaroo, kangaroo care',
                            'philippines, filipino, philippine airlines', 'christmas, christmas tree, christmas eve',
                            'office worker, salaryman', 'vera cruz, veracruz, siege of veracruz',
                            'chocolate, chocolate cake, chocolate fountain', 'condominium, salon, mansion house',
                            'computer, computer game, pc game', 'cylinder, cylinder lock, cylinder oil',
                            'packing, packing-case, packing-paper', 'schedule, diary, scheduling',
                            'chili sauce, hot sauce', 'gym, health club, sport climbing',
                            'passport, passport to paris, passport card', 'allergy, aversion, allergic rhinitis',
                            'dining, dining room, meal', 'calendar, calender, calendar program',
                            'olympics, olympic event, olympic sports', 'escalator, escalation',
                            'program, program manager', 'ticket agency', 'key word, keyword, index term',
                            'party, party dress, party people', 'brochure, pamphlet', 'picnic, outing, picnic table',
                            'indonesia, indonesian', 'operations manual, user guide, manual focus',
                            'singapore, singapore airlines, singapore telecom', 'helmet, stahlhelm, motorcycle helmet',
                            'percent, percentage, percent sign', 'coupler, cup noodles', 'hiking, hiking trail',
                            'ball-point pen, ballpoint pen', 'diet, losing weight, dieting',
                            'part-time job, part-time worker, albite', 'franken, frankenstein',
                            'volunteer, volunteering', 'meeting, meeting room, meeting venus',
                            'pyramid, pyramid selling, pyramid-style', 'shampoo, blow dry',
                            'hamburg steak, salisbury steak', 'los angeles, death wish ii', 'mechanical pencil',
                            'contest, contesting', 'munich, munchen, beer hall putsch', 'airmail', 'coin locker babies',
                            'europe, european, european robin', 'classical music, classic, classic cycle races',
                            'jogging, jogging shoes, jogging pants', 'cassette tape', 'seat belt, seatbelt sign',
                            'whisky, whisky sour, whisky bonbon', 'engineer, engineering, engineering plastic',
                            'cache, cash, cash card', 'new york, new yorker', 'captain, hms captain, captain jacket',
                            'instant, instant ramen, instant noodles', 'telephone card', 'beethoven, beethoven virus',
                            'cancellation, waiting list, cancel culture', 'cellophane tape',
                            'concert, concert hall, concert master', 'start button',
                            'malaysia, malaysia airlines, malaysian person',
                            'internet, internet site, internet television', 'office worker, salaryman',
                            'coin locker babies', 'schedule, diary', 'cassette tape', 'cleaning, laundry',
                            'mechanical pencil', 'seat belt, seatbelt sign',
                            'singapore, singapore airlines, singapore telecom', 'california', 'homestay',
                            'start button', 'tape recorder', 'cash card, atm card',
                            'instant, instant ramen, instant noodles', 'ticket agency', 'volleyball',
                            'indonesia, indonesian', 'volunteer, volunteering',
                            'chocolate, chocolate cake, chocolate fountain', 'new york, new york city, uss new york',
                            'computer, computer game, pc game', 'olympics, olympic event, olympic sports',
                            'escalator, escalator clause', 'cup noodles', 'telephone card', 'brochure, pamphlet',
                            'party room', 'beethoven, beethoven virus', 'gym, health club, sport climbing',
                            'meeting, meeting room, meeting venus', 'elevator, elevator operator, elevator landing',
                            'los angeles, death wish ii, uss los angeles', 'influenza, influence, influenza virus',
                            'eat-in kitchen', 'cash card, atm card', 'tape recorder', 'cup noodles', 'telephone card',
                            'cassette tape', 'eat-in kitchen', 'gym, health club', 'california, california condor',
                            'computer, computer game, pc game', 'coin locker babies',
                            'influenza, influenza virus, flu vaccine', 'mechanical pencil', 'party room',
                            'internet, internet site, internet auction', 'escalator, escalator clause',
                            'instant ramen, instant noodles', 'start button']
